ToDoListApp/Models/ApplicationUser.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;

namespace ToDoListApp.Models
{
    public class ApplicationUser : IdentityUser
    {
    }
}

ToDoListApp/Models/ErrorViewModel.cs
using System;

namespace ToDoListApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoListApp/Models/ToDoListTask.cs
using System;
using System.ComponentModel.DataAnnotations;


namespace ToDoListApp.Models
{
    public class ToDoListTask
    {
        public Guid Id { get; set; }

        public bool IsDone { get; set; }

        [Required]
        public string Title { get; set; }

        public string Details { get; set; }

        public DateTime DateModified { get; set; }

        public string UserId { get; set; }
    }
}

ToDoListApp/Models/ToDoListViewModel.cs


namespace ToDoListApp.Models
{
    public class ToDoListViewModel
    {
        public ToDoListTask[] Tasks { get; set; }
    }
}

ToDoListApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ToDoListApp.Models;

namespace ToDoListApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDoListApp/Controllers/ToDoListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ToDoListApp.Services;
using ToDoListApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace ToDoListApp.Controllers
{
    [Authorize]
    public class ToDoListController : Controller
    {
        private readonly IToDoListTaskService _toDoListTaskService;
        private readonly UserManager<ApplicationUser> _userManager;

        public ToDoListController(IToDoListTaskService toDoListTaskService, UserManager<ApplicationUser> userManager)
        {
            _toDoListTaskService = toDoListTaskService;
            _userManager = userManager;
        }


        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null) return Challenge();

            var tasks = await _toDoListTaskService.GetUnfinishedTasksAsync(currentUser);

            var model = new ToDoListViewModel()
            {
                Tasks = tasks
            };

            return View(model);
            
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTask(ToDoListTask newTask)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null) return Challenge();


            var successful = await _toDoListTaskService.AddTaskAsync(newTask, currentUser);
            if (!successful)
            {
                return BadRequest("Failed to add task.");
            }

            return RedirectToAction("Index");
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MarkDone(Guid id)
        {
            if (id == Guid.Empty)
            {
                return RedirectToAction("Index");
            }

            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null) return RedirectToAction("Index");

            var successful = await _toDoListTaskService.MarkDoneAsync(id, currentUser);
            if (!successful)
            {
                return BadRequest("Could not mark task as done.");
            }

            return RedirectToAction("Index");
        }

    }
}

ToDoListApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="text-center">
    <p> <a asp-controller="ToDoList" >Click Here to view your ToDo List</a>.</p>
</div>

ToDoListApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoListApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoListApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDoList" asp-action="Index">My ToDo List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ToDoListApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ToDoListApp/Views/ToDoList/AddTaskPartial.cshtml
@model ToDoListTask


<form asp-action="AddTask" method="POST">
    <div class="form-group">
        <label for="Title" required>Add a new task:</label>
        <input asp-for="Title" type="text" class="form-control" placeholder="Enter Task">
    </div>
    <div class="form-group">
        <label asp-for="Details">Details(Optional):</label>
        <input asp-for="Details" type="text" class="form-control" placeholder="Enter Details">
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>

ToDoListApp/Views/ToDoList/Index.cshtml
@model ToDoListViewModel

@{
    ViewData["Title"] = "Your ToDo list: ";
}

<div class="panel panel-default todo-panel">
    <div class="panel-heading">@ViewData["Title"]</div>

    <table class="table table-hover table-light table-striped">
        <thead class="thead-dark">
            <tr>
                <th>Done</th>
                <th>Task</th>
                <th>Details</th>
                <th>Last Modified</th>
            </tr>
        </thead>

        @foreach (var task in Model.Tasks)
      {
        <tr>
            <td>
                <form asp-action="MarkDone" method="POST">
                    <input type="checkbox" class="done-checkbox">
                    <input type="hidden" name="id" value="@task.Id">
                </form>
            </td>
            <td>@task.Title</td>
            <td>@task.Details</td>
            <td>@task.DateModified</td>
        </tr>
      }
    </table>

    <div class="panel-footer add-item-form ">
        @await Html.PartialAsync("AddTaskPartial", new ToDoListTask())
    </div>
</div>